import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/custom.scss";
import React from "react";


import BootstrapClient from '@/components/BootstrapClient';
import {PrimeReactProvider} from "primereact/api";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
      <PrimeReactProvider value={{ unstyled: true }}>
        {children}
        <BootstrapClient />
      </PrimeReactProvider>
      </body>
    </html>
  );
}
